### ISSUE TITLE
client secrets prompt is not triggered when .client file is present but invalid

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/n5-google-cloud#6]
Steps to reproduce:
```bash
echo '' > ~/.google/n5-google-cloud/.client 
```
```java
public class EmptyFileError
{
	public static void main( final String[] args ) throws IOException
	{
		final GoogleCloudOAuth gcoa = new GoogleCloudOAuth( new GoogleCloudClientSecretsCmdLinePrompt() );
	}
}
```

Exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: no JSON input found
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:49)
	at com.google.api.client.json.JsonParser.startParsing(JsonParser.java:223)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:380)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:336)
	at com.google.api.client.json.JsonParser.parseAndClose(JsonParser.java:166)
	at com.google.api.client.json.JsonParser.parseAndClose(JsonParser.java:148)
	at com.google.api.client.json.JsonFactory.fromReader(JsonFactory.java:236)
	at com.google.api.client.googleapis.auth.oauth2.GoogleClientSecrets.load(GoogleClientSecrets.java:192)
	at org.janelia.saalfeldlab.googlecloud.GoogleCloudOAuth.loadClientSecrets(GoogleCloudOAuth.java:137)
	at org.janelia.saalfeldlab.googlecloud.GoogleCloudOAuth.<init>(GoogleCloudOAuth.java:77)
	at org.janelia.saalfeldlab.googlecloud.GoogleCloudOAuth.<init>(GoogleCloudOAuth.java:60)
	at org.janelia.saalfeldlab.googlecloud.GoogleCloudOAuth.<init>(GoogleCloudOAuth.java:49)
	at org.janelia.saalfeldlab.googlecloud.EmptyFileError.main(EmptyFileError.java:10)
```

Instead of [`File.exists`](https://github.com/saalfeldlab/n5-google-cloud/blob/a4844c4473c6e0f19ede8d2110e7434632f26f43/src/main/java/org/janelia/saalfeldlab/googlecloud/GoogleCloudOAuth.java#L76) this should probaly be handled via `try`/`except`.

**Comment by igorpisarev** [comment]
Thanks @hanslovsky for catching this. There are more related problems that I tried to list in #8 (the list is probably not exhaustive).

**Comment by igorpisarev** [comment]
This is not relevant anymore as authentication is now done using `gcloud`.
