### ISSUE TITLE
Code 409 Conflict on current master when calling N5GoogleCloudStorageWriter constructor

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/n5-google-cloud#9]
Opening a google cloud bucket in paintera fails with 

```
com.google.cloud.storage.StorageException: You already own this bucket. Please select another name.
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:220)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:263)
	at com.google.cloud.storage.StorageImpl$2.call(StorageImpl.java:112)
	at com.google.cloud.storage.StorageImpl$2.call(StorageImpl.java:109)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
	at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:108)
	at org.janelia.saalfeldlab.n5.googlecloud.N5GoogleCloudStorageWriter.<init>(N5GoogleCloudStorageWriter.java:76)
	at org.janelia.saalfeldlab.n5.googlecloud.N5GoogleCloudStorageWriter.<init>(N5GoogleCloudStorageWriter.java:91)
	at org.janelia.saalfeldlab.paintera.ui.opendialog.N5BackendDialogs.lambda$21(N5BackendDialogs.java:146)
	at org.janelia.saalfeldlab.util.MakeUnchecked.lambda$3(MakeUnchecked.java:80)
	at java.util.Optional.map(Optional.java:215)

// irrelevant stuff

Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 409 Conflict
{
  "code" : 409,
  "errors" : [ {
    "domain" : "global",
    "message" : "You already own this bucket. Please select another name.",
    "reason" : "conflict"
  } ],
  "message" : "You already own this bucket. Please select another name."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:260)
	... 161 more

```

The dependency is n5-google-cloud master, which is currently at cbdf7ae
When I depend on `2.3.1` everything works as expected.

**Comment by igorpisarev** [comment]
Thanks @hanslovsky, I must have accidentally missed it while changing how the test mocking library is handled (it does not support bucket creation API, for example, which requires extra checking)
